{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "50bfc330",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import required packages\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import json\n",
    "import dash\n",
    "from dash import dcc\n",
    "from dash import html\n",
    "import plotly.express as px\n",
    "import plotly.graph_objs as go\n",
    "from dash.dependencies import Input, Output\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "98b165fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [21/Sep/2022 11:15:18] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:15:27] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [21/Sep/2022 11:15:27] \"GET /_dash-layout HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "# Add Dataframe\n",
    "df = pd.DataFrame({\n",
    "    \"Fruit\": [\"Apples\", \"Oranges\", \"Bananas\", \"Apples\", \"Oranges\", \"Bananas\"],\n",
    "    \"Amount\": [4, 1, 2, 2, 4, 5],\n",
    "    \"City\": [\"San Francisco\", \"San Francisco\", \"San Francisco\", \"New York City\", \"Montréal\", \"New York City\"]\n",
    "})\n",
    "\n",
    "# Add a bar graph figure\n",
    "#fig = px.bar(df, x=\"Fruit\", y=\"Amount\", color=\"City\", barmode=\"group\")\n",
    "\n",
    "\n",
    "app = dash.Dash()\n",
    "app.layout = html.Div(children=[\n",
    "    html.H1(\n",
    "        children='Dashboard',\n",
    "        style={\n",
    "            'textAlign': 'center'\n",
    "        }\n",
    "    ), \n",
    "    # Create dropdown\n",
    "     html.Div([\n",
    "    dcc.Dropdown(['New York City', 'Montréal', 'San Francisco'], 'New York City')\n",
    "]), \n",
    "    # Bar graph\n",
    "    dcc.Graph(\n",
    "        id='example-graph-2',\n",
    "        figure={\n",
    "            'data': df,\n",
    "            'layout': go.Layout(title='Order Status by city', barmode='group')\n",
    "        })\n",
    "   ])\n",
    "\n",
    "# Run Application\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e8001fb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:44] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:45] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_6_1m1663187175.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:45] \"GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_6_1m1663187171.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:45] \"GET /_dash-component-suites/dash/deps/react-dom@16.v2_6_1m1663187177.14.0.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:45] \"GET /_dash-component-suites/dash/deps/react@16.v2_6_1m1663187177.14.0.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:45] \"GET /_dash-component-suites/dash/deps/polyfill@7.v2_6_1m1663187177.12.1.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:45] \"GET /_dash-component-suites/dash/deps/prop-types@15.v2_6_1m1663187177.8.1.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:46] \"GET /_dash-component-suites/dash/html/dash_html_components.v2_0_5m1663187181.min.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:46] \"GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_6_1m1663187175.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:47] \"GET /_dash-component-suites/dash/dash_table/bundle.v5_1_5m1663187172.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [21/Sep/2022 11:32:48] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [21/Sep/2022 11:32:48] \"GET /_favicon.ico?v=2.6.1 HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n",
      "Exception on /_dash-layout [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\dash.py\", line 646, in serve_layout\n",
      "    to_json(layout),\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\dash\\_utils.py\", line 22, in to_json\n",
      "    return to_json_plotly(value)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\plotly\\io\\_json.py\", line 123, in to_json_plotly\n",
      "    return json.dumps(plotly_object, cls=PlotlyJSONEncoder, **opts)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\__init__.py\", line 234, in dumps\n",
      "    return cls(\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 59, in encode\n",
      "    encoded_o = super(PlotlyJSONEncoder, self).encode(o)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\site-packages\\_plotly_utils\\utils.py\", line 136, in default\n",
      "    return _json.JSONEncoder.default(self, obj)\n",
      "  File \"C:\\Users\\Sharon\\anaconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type DataFrame is not JSON serializable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [21/Sep/2022 11:32:48] \"GET /_dash-layout HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "df = pd.DataFrame({\n",
    "    \"Fruit\": [\"Apples\", \"Oranges\", \"Bananas\", \"Apples\", \"Oranges\", \"Bananas\"],\n",
    "    \"Amount\": [4, 1, 2, 2, 4, 5],\n",
    "    \"City\": [\"San Francisco\", \"San Francisco\", \"San Francisco\", \"New York City\", \"Montréal\", \"New York City\"]\n",
    "})\n",
    "\n",
    "# Add a bar graph figure\n",
    "#fig = go.bar(df, x=\"Fruit\", y=\"Amount\", color=\"City\", barmode=\"group\")\n",
    "\n",
    "# Bar graph\n",
    "   \n",
    "app = dash.Dash()\n",
    "\n",
    "app.layout =  html.Div(children=[\n",
    "    html.H1(\n",
    "        children='Dashboard',\n",
    "        style={\n",
    "            'textAlign': 'center'\n",
    "        }\n",
    "    ), \n",
    "    # Create dropdown\n",
    "     html.Div([\n",
    "    dcc.Dropdown(['New York City', 'Montréal', 'San Francisco'], 'New York City')\n",
    "]),\n",
    "dcc.Graph(\n",
    "        id='example-graph-2',\n",
    "        figure={\n",
    "            'data': df,\n",
    "            'layout':\n",
    "            go.Layout(title='Order Status by city', barmode='group')\n",
    "        })\n",
    "]) \n",
    "# Run Application\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "bbfd0b1c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Fruit</th>\n",
       "      <th>Amount</th>\n",
       "      <th>City</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Apples</td>\n",
       "      <td>4</td>\n",
       "      <td>San Francisco</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Oranges</td>\n",
       "      <td>1</td>\n",
       "      <td>San Francisco</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Bananas</td>\n",
       "      <td>2</td>\n",
       "      <td>San Francisco</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Apples</td>\n",
       "      <td>2</td>\n",
       "      <td>New York City</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Oranges</td>\n",
       "      <td>4</td>\n",
       "      <td>Montréal</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Bananas</td>\n",
       "      <td>5</td>\n",
       "      <td>New York City</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "     Fruit  Amount           City\n",
       "0   Apples       4  San Francisco\n",
       "1  Oranges       1  San Francisco\n",
       "2  Bananas       2  San Francisco\n",
       "3   Apples       2  New York City\n",
       "4  Oranges       4       Montréal\n",
       "5  Bananas       5  New York City"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.DataFrame({\n",
    "    \"Fruit\": [\"Apples\", \"Oranges\", \"Bananas\", \"Apples\", \"Oranges\", \"Bananas\"],\n",
    "    \"Amount\": [4, 1, 2, 2, 4, 5],\n",
    "    \"City\": [\"San Francisco\", \"San Francisco\", \"San Francisco\", \"New York City\", \"Montréal\", \"New York City\"]\n",
    "})\n",
    "df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce174f6a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
